# Generated by Django 3.0.5 on 2020-08-17 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traxBotWeb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
