# Generated by Django 3.0.5 on 2020-08-17 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traxBotWeb', '0002_auto_20200816_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='xPos',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='position',
            name='yPos',
            field=models.FloatField(),
        ),
    ]
